
dbt_dimensional_demo:

  outputs:

    postgresAdventure:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: '10042076'
      database: Adventureworks
      schema: target  # this is override in each model's sql

    duckdb:
      # https://docs.getdbt.com/reference/warehouse-setups/duckdb-setup
      type: duckdb
      path: target/AdventureworksDW.duckdb
      threads: 4


    # https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables
    # C:\ProgramData\Miniconda3\envs\powerbi\etc\conda\activate.d
    # C:\ProgramData\Miniconda3\envs\powerbi\etc\conda\deactivate.d

    supabaseAdventure:
      type: postgres
      threads: 4
      host: "{{ env_var('SUPABASE_HOST') }}"
      port: 5432
      user: "{{ env_var('SUPABASE_USER') }}"
      pass: "{{ env_var('SUPABASE_PASS') }}"
      database: Adventureworks
      schema: t
    
    auroraAdventure:
      type: postgres
      threads: 4
      host: "{{ env_var('AURORA_HOST') }}"
      port: 5432
      user: "{{ env_var('AURORA_USER') }}"
      pass: "{{ env_var('AURORA_PASS') }}"
      database: Adventureworks
      schema: t

    #prod:
    #  type: postgres
    #  threads: [1 or more]
    #  host: [host]
    #  port: [port]
    #  user: [prod_username]
    #  pass: [prod_password]
    #  dbname: [dbname]
    #  schema: [prod_schema]

  target: postgresAdventure
