
dbt_dimensional_demo:

  outputs:

    postgresAdventure:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: '10042076'
      database: Adventureworks
      schema: target

    duckdb:
      # https://docs.getdbt.com/reference/warehouse-setups/duckdb-setup
      type: duckdb
      path: target/AdventureworksDW.duckdb
      threads: 4

    supabaseAdventure:
      # https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables
      type: postgres
      threads: 4
      host: "{{ env_var('SUPABASE_HOST') }}"
      port: 5432
      user: "{{ env_var('SUPABASE_USER') }}"
      pass: "{{ env_var('SUPABASE_PASS') }}"
      database: Adventureworks
      schema: t


    #prod:
    #  type: postgres
    #  threads: [1 or more]
    #  host: [host]
    #  port: [port]
    #  user: [prod_username]
    #  pass: [prod_password]
    #  dbname: [dbname]
    #  schema: [prod_schema]

  target: supabaseAdventure
